### ISSUE TITLE
Crash related to sendPlaySoundPacket

### ISSUE THREAD

**Issue by ChromaPIE** [TCreopargh/CraftTweakerIntegration#2]
（国际平台用英文 方便你我他）
Only happens in multiplayer, causing players excluding the server host to be disconnected from the server when activating [this](https://paste.ubuntu.com/p/xj5nzk8Vkx/) event.

Log (only related section): https://paste.ubuntu.com/p/PK75twF4nN/

**Comment by TCreopargh** [comment]
Looks like you are not setting a valid sound category, should be one of `master`, `music`, `record`, `weather`, `block`, `hostile`, `neutral`, `player`, `ambient`, or `voice`
