### ISSUE TITLE
Wiki: IWorld.playSound() actually don't need world as first param

### ISSUE THREAD

**Issue by Krutoy242** [TCreopargh/CraftTweakerIntegration#4]
`IWorld.playSound` shouldn't have `IWorld world` as first parameter, because we already calling function from IWorld instance. Also, giving IWorld as first param we got an CT error:
```java
a method available but none matches the parameters (ZenTypeNative: crafttweaker.world.IWorld, string, string, ZenTypeNative: crafttweaker.util.Position3f, float, float)
This is usually an error in your script, not in the mod
playSound(ZenTypeNative: crafttweaker.world.IWorld, string, string, ZenTypeNative: crafttweaker.util.Position3f, float, float, Optional bool)
```

**Comment by TCreopargh** [comment]
The first parameter is used to pass the object on which the method is called to java and shouldn't appear in the wiki. The wiki should be already corrected.
