### ISSUE TITLE
DateUtil.now().month 所获取的月份为上个月份

### ISSUE THREAD

**Issue by Dark2932** [TCreopargh/CraftTweakerIntegration#6]
如标题所说，调用这个方法会返回当前月份的上个月份
比如现在是7月，那么调用这个方法会返回 6
如果月份为 1月，那么会返回 0 
调用这个方法时再 +1 就能解决，但还是想反馈下

使用 DateUtil.now() 出来的月份结果是正确的，是正常的月份

**Comment by TCreopargh** [comment]
Java的Calendar API本身如此，月份从0开始，转换成一般月份需要+1
